### ISSUE TITLE
4A: Define APIs between modules

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/bms-fw#54]
This task mainly focuses on refactoring at the module level and *defining responsibilities for modules.
* we should decentralize initialization code and dissolve it into separate modules where there is a single owner

Output:
- Task skeletons
- Queue modules

**Comment by rafguevara14** [comment]
The work is already done in this repo. We just need to integrate it into the BMS code https://github.com/sfuphantom/hercules-phantom-lib
