### ISSUE TITLE
4B: Define queue mailbox wrapper

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/bms-fw#55]
There needs to be communication between the sensors and the state machine, freertos queues are used for this. 

The github for more information: https://github.com/sfuphantom/firmware/tree/Queue-Prototype/queue-pipeline

**Comment by rafguevara14** [comment]
This can already done by the event handler module in https://github.com/sfuphantom/hercules-phantom-lib/tree/main. See vcu-fw for application details with a state machine
