### ISSUE TITLE
4C: Implement BMS CLI

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/bms-fw#56]
There’s gonna be a lot of sensors on the BMS. Would be nice to see them in real time by just pressing certain keys. VCU has the basics of this implemented https://github.com/sfuphantom/vcu-fw

https://github.com/sfuphantom/bms-fw/tree/BMS-4C-Implement-CLI

Output:
- Readme explaining commands
- Quick demo would be cool

**Comment by rafguevara14** [comment]
Moved to https://github.com/sfuphantom/hercules-phantom-lib/issues/2
